### ISSUE TITLE
Wrong conversion negative temperature

### ISSUE THREAD

**Issue by wolfganghuse** [rnlgreen/thermobeacon#1]
Hello, seems your conversion has a issue as soon as there is a negative temperature value i got a value around 4095.9 displayed. 

Regards,
Wolfgang

**Comment by rnlgreen** [comment]
Hmm, that's a bit odd, there's logic in there to subtract 4096 from high values to deal with negative temperatures, I thought that worked. I'm not using the sensors anymore myself but I'll dig one out and see if I can validate that.
